# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo build FirstJob
  - job: SecondJob
    steps:
    - bash: echo Build SecondJob
- stage: DevDeploy
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo build firstJob!!
- stage: qaDeploy
  jobs:
  - job: qaDeployJob
    steps:
    - bash: echo build QA Job!!
- stage: ProdDeploy
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo build prod Job!!
